### ISSUE TITLE
Add Header for adapter meet a problem

### ISSUE THREAD

**Issue by XinYiWorld** [Jude95/EasyRecyclerView#16]
Here is the fragmen of my code：
` List<String> data = new ArrayList<>();
        for(int i = 0; i < 20; i ++){
            data.add("position:" + i);
        }
        testAdapter = new testAdapter(this);
        testAdapter.addHeader(new RecyclerArrayAdapter.ItemView() {
            @Override
            public View onCreateView(ViewGroup parent) {
                View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.adapter_test, null, false);
                return view;
            }

```
        @Override
        public void onBindView(View headerView) {
            TextView header = (TextView) headerView.findViewById(R.id.header);
            header.setText("I'M HEADER");
        }
    });

    testAdapter.notifyDataSetChanged();
    testAdapter.addAll(data);
    rcv.setAdapter(testAdapter);
    rcv.setLayoutManager(new LinearLayoutManager(this));` 
```

Here is the exception caught:
FATAL EXCEPTION: main
                                                                                          Process: com.example.zhang.recyclerviewwithheader, PID: 29336
                                                                                          java.lang.NullPointerException
                                                                                              at android.view.ViewGroup$LayoutParams.<init>(ViewGroup.java:5929)
                                                                                              at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6211)
                                                                                              at android.support.v7.widget.RecyclerView$LayoutParams.<init>(RecyclerView.java:8742)
                                                                                              at android.support.v7.widget.StaggeredGridLayoutManager$LayoutParams.<init>(StaggeredGridLayoutManager.java:2050)
                                                                                              at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.createSpViewByType(RecyclerArrayAdapter.java:407)
                                                                                              at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.onCreateViewHolder(RecyclerArrayAdapter.java:427)
                                                                                              at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.onCreateViewHolder(RecyclerArrayAdapter.java:49)
                                                                                              at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5288)
                                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4551)
                                                                                              at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
                                                                                              at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)
                                                                                              at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1371)
                                                                                              at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)
                                                                                              at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
                                                                                              at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2847)
                                                                                              at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                              at com.jude.easyrecyclerview.swipe.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:546)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                              at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                              at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                              at android.view.View.layout(View.java:14828)
                                                                                              at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2074)
                                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1831)
                                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1087)
                                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5696)
                                                                                            at android.view.Ch

**Comment by Jude95** [comment]
try this:
View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.adapter_test, **parent**, false);
and check if `view == null`

**Comment by XinYiWorld** [comment]
Thanks for your fast answer,your project is great.But event if i return a new TextView(),the problem is still there,have you test the method addHeader()? 
the exception is appear before onCreateView()....

**Comment by XinYiWorld** [comment]
my app requires me to diplay the last refresh time while refreshing,can you give me an advice,thank?

**Comment by Jude95** [comment]
the demo works well with Header.
I think the problem is the LayoutParams.
`inflate.inflate(id, null, false)` will return a view with null LayoutParams,so I give `parent` in params.
`new TextView()`also should `setLayoutParams`.
have you try this?

the last refresh time...I give up it for SwipeRefreshLayout.I don't konw where to show it with SwipeRefreshLayout.

**Comment by Jude95** [comment]
This problem solved?is there any other question?

**Comment by XinYiWorld** [comment]
Thanks for your care,it's solved by adding layoutparams for the itemview.
Your project is really really easy to use,considering to add the date on refresh header,I will chose pulltorefresh this time.

**Comment by Awekbing** [comment]
我也遇到这个问题   顺便分享下
onCreateViewHolder 这里如果根据viewType设置多个样式的view一定要记得  把null处理掉
我也是因为这个原因导致的
android.support.v7.widget.ActionBarOverlayLayout.onLayout  抛出异常
