### ISSUE TITLE
有时会这样，请问什么问题呢

### ISSUE THREAD

**Issue by Itachi6688** [Jude95/EasyRecyclerView#168]
java.lang.ArrayIndexOutOfBoundsException: length=28; index=-1
	at java.util.ArrayList.get(ArrayList.java:310)
	at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.getItem(RecyclerArrayAdapter.java:668)
	at com.jwbc.cn.ui.fragment.task.WXHistoryTaskFragment.onItemClick(WXHistoryTaskFragment.java:123)
	at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter$3.onClick(RecyclerArrayAdapter.java:588)

**Comment by xkdwby** [comment]
你添加header了吗

**Comment by Itachi6688** [comment]
有些加了 有些没加 不管加不加有时都会这样

**Comment by star-andy** [comment]
@Itachi110   我现在也遇见这个问题了，后台日志上能看见这个崩溃的bug，但是我无法复现 ，请问下  你解决这个问题了吗？

**Comment by Itachi6688** [comment]
@qinyang1018 换框架吧
