### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by NitroXenon** [Jude95/EasyRecyclerView#17]
不知道这个FC是不是Easy RecyclerView造成...

```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getY(MotionEvent.java:1996)
       at android.support.v4.view.MotionEventCompatEclair.getY(Unknown Source)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getY(Unknown Source)
       at android.support.v4.view.MotionEventCompat.getY(Unknown Source)
       at com.jude.easyrecyclerview.swipe.SwipeRefreshLayout.onTouchEvent(Unknown Source)
       at android.view.View.dispatchTouchEvent(View.java:7127)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2144)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1905)
       at com.jude.easyrecyclerview.swipe.SwipeRefreshLayout.dispatchTouchEvent(Unknown Source)
       at com.jude.easyrecyclerview.EasyRecyclerView.dispatchTouchEvent(Unknown Source)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2146)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2146)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2146)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2146)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2146)
       at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1812)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1877)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1942)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1380)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2510)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1890)
       at android.view.View.dispatchPointerEvent(View.java:7307)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3174)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3119)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4155)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4134)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4226)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:124)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Jude95** [comment]
可以描述下，怎么操作造成的FC？

**Comment by NitroXenon** [comment]
具体不清楚。。。Crashlytics回报的。。。

**Comment by Jude95** [comment]
...SwipeRefreshLayout的错误，我试着把它更新为最新的版本吧(现在的这个类是我从support库里复制修改的，但并没有改手势处理部分)。
仅凭这个log也找不出具体bug，错误不多吧...

**Comment by NitroXenon** [comment]
這個只有1次報錯...

**Comment by NitroXenon** [comment]
加油!! 這個很好用!!

**Comment by EFEXP** [comment]
I was faced with same problem.
It may be caused by this code (written by kotlin) and like this 

``` kotlin
    val  data:ArrayList<String> = ArrayList<String>()
    val  mAdapter=MyRecyclerAdapter(activity, data) 
    ....
    data.add(0,"string")
    mAdapter.notifyItemInserted(0)
```

Change this into below 

``` kotlin
    val  data:ArrayList<String> = ArrayList<String>()
    val  mAdapter=MyRecyclerAdapter(activity, "string") 
    ....
  mAdapter.insert(it,0)
```

It was fixed at my environment.
