### ISSUE TITLE
偶现 返回的postion为-1

### ISSUE THREAD

**Issue by weiweiForAndroid** [Jude95/EasyRecyclerView#272]
java.lang.ArrayIndexOutOfBoundsException: length=20; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.getItem(RecyclerArrayAdapter.java:667)

  if (mItemClickListener!=null) {
            viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    mItemClickListener.onItemClick(viewHolder.getAdapterPosition()-headers.size());
                }
            });
        }

返回的postion为-1

**Comment by lijunhuayc** [comment]
public void onClick(View v) {
mItemClickListener.onItemClick(viewHolder.getAdapterPosition()-headers.size());
}
});
}
这里应该使用viewHolder.getLayoutPosition()吧
