### ISSUE TITLE
加载更多问题。

### ISSUE THREAD

**Issue by ghost** [Jude95/EasyRecyclerView#42]
mEasyRvAdapter = new EasyRvAdapter(mContext);
        recyclerView.setLayoutManager(new LinearLayoutManager(mContext));
        recyclerView.setAdapter(mEasyRvAdapter);
        mEasyRvAdapter.addAll(DataServer.getDataFive());
        mEasyRvAdapter.setMore(R.layout.view_more, new RecyclerArrayAdapter.OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                Log.d(TAG, "onLoadMore");
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mEasyRvAdapter.addAll(DataServer.getDataMore());
                    }
                }, 2000);
            }
        });
我直接这样写，应该是可以实现加载更多的那个功能的吧。但是实际，却没有，滑动到底部还是不行，不过我用的是RecyclerView ，不是EasyRecyclerView。
还有就是，我直接clone项目，运行，在CollapsingActivity.java，将EasyRecyclerView 替换为RecyclerView ，第一次加载更的时候，不会显示loading view ，往后的第二，第三次，才有。不过代码还没细看，回家在看看，不知道是我的用法有问题，还是其他的问题。

**Comment by ghost** [comment]
一定要延时加载数据吗，类似handler.postDelayed这样

**Comment by Jude95** [comment]
确实，是上个版本改出了个这个bug。在OnCreateViewHolder之前添加数据引起的状态变化被忽略了。
3.5.6看看还有没有问题。

**Comment by ghost** [comment]
CollapsingActivity.java中，adapter.setMore那里，把加载数据换成， adapter.stopMore();或者 adapter.pauseMore();出现了
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
                                                                 at com.jude.easyrecyclerview.adapter.DefaultEventDelegate$EventFooter.refreshStatus(DefaultEventDelegate.java:187)
                                                                 at com.jude.easyrecyclerview.adapter.DefaultEventDelegate$EventFooter.showError(DefaultEventDelegate.java:197)
                                                                 at com.jude.easyrecyclerview.adapter.DefaultEventDelegate.pauseLoadMore(DefaultEventDelegate.java:96)
                                                                 at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.pauseMore(RecyclerArrayAdapter.java:230)
                                                                 at com.jude.dome.collapsing.CollapsingActivity$1$1.run(CollapsingActivity.java:60)

不过我在前面加了句adapter.setNoMore(R.layout.view_nomore);
onLoadMore里，换成adapter.stopMore(); 没问题，换成adapter.pauseMore();出错。

**Comment by Jude95** [comment]
恩。对,没有setNoMore就不能显示nomore。没有设置setError就不能显示error。一强制显示就会这样。
我还没有对这个做限制。我修改一下。应该抛出指定错误，还是不报错直接不显示好？

**Comment by ghost** [comment]
感觉stop或者pause都可以指向一种状态。一般情况下，都是上拉加载，然后去服务器请求，请求得到的结果无非就是成功或者失败。
1、失败的话，显示error msg，其实这个状态就已经是stop或者pause了。
2、成功就显示更多数据，等待下一次加载更多。
上拉加载，最好还是滚动到底部触发，而不是底部可见触发，这主要还是针对，数据太少，铺不满屏幕的情况，不过实际情况还是比较少遇到的。
请求时，即使滚动到底部再次触发，也要忽略。个人拙见。
装了个软件，点击了重启生效，忘记保存，还好，记录还在。。

**Comment by Jude95** [comment]
pause是本页数据加载错误。会自动重新加载，你也能手动重新加载。  
stop表示所有数据加载完毕，显示没有更多数据(不要说没这个需求，不需要不设置就好，都是你们要的)。

铺不满屏幕时，没有滚动，你不手动停止肯定要自动回调第二页，直到铺满。这个逻辑没错吧？我第一页就是没铺满屏幕，不应该自动加载第二页填补下面的空吗。

不同的问题请新建issue。
