### ISSUE TITLE
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by liyuzhao** [Jude95/EasyRecyclerView#65]
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

crash bug, who can help me ?

**Comment by Jude95** [comment]
What did you do?Please paste the code and describe it in detail.

**Comment by JohnsonChan** [comment]
我也遇到相同的问题，不知道怎么解决。

**Comment by Jude95** [comment]
@JohnsonChan 能贴下你的代码，及这个crash的触发情景，频率，机型，android版本，support包版本？

**Comment by jiugege** [comment]
我也遇到了这个问题求解决

**Comment by crysehillmes** [comment]
同样遇到了这个问题。

**Comment by da1go** [comment]
I have the same issue. no idea for what the reason.

Does this PR resolve the issue ? https://github.com/Jude95/EasyRecyclerView/pull/50

**Comment by xiaotian-freedom** [comment]
@Jude95 java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
    at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(SourceFile:5231)
    at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(SourceFile:5302)
    at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(SourceFile:7736)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(SourceFile:3388)
    at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3135)
    at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3568)
    at android.view.View.layout(View.java:15728)
    at android.view.ViewGroup.layout(ViewGroup.java:5050)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at com.jude.easyrecyclerview.swipe.SwipeRefreshLayout.onLayout(SourceFile:548)
    at android.view.View.layout(View.java:15728)
    at android.view.ViewGroup.layout(ViewGroup.java:5050)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15728)
    at android.view.ViewGroup.layout(ViewGroup.java:5050)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1734)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1588)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
    at android.view.View.layout(View.java:15728)
    at android.view.ViewGroup.layout(ViewGroup.java:5050)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
这是我的崩溃日志，android 6.0.1 (23)，Xiaomi:MI NOTE LTE:armeabi-v7a，support：24.2.0

**Comment by Jude95** [comment]
@xiaotianyilang 试试4.2.5以后的版本还有吗。是上周更新的。

**Comment by xiaotian-freedom** [comment]
@Jude95 是什么原因造成的？这个问题我自己没碰到过，是线上的用户反馈的，是因为SwipeRefreshLayout这个类造成的吗？

**Comment by Jude95** [comment]
与SwipeRefreshLayout物管，怀疑是removeItem与addItem有些同步问题，具体也不清楚，stackOverFlow里搜索造成这个错误的原因也很多。应该是RecyclerView自己的BUG。你在github里面搜相关的issue，很多库也都有这个问题。

**Comment by xiaotian-freedom** [comment]
@Jude95 能否把 MVP框架中的easyRecyclerView版本更新一下，框架中集成的easyRecyclerView会出现这个问题

**Comment by xuyt11** [comment]
public void addAllData(List<T> projects, boolean isLoadMore) {
        if (isLoadMore) {
             adapter.addAll(projects);
        } else {// refresh data
            recyclerView.setRefreshing(false);
            if ( adapter.getCount() > 0) {
                 adapter.clear();
                 adapter.addAll(projects);
                 adapter.notifyDataSetChanged();
            } else {
                adapter.addAll(projects);
            }
        }
    }

http://www.jianshu.com/p/c8610c9391cb

**Comment by star-andy** [comment]
最近项目很多机型报这个错误   使用的是4.4.0版本
![image](https://cloud.githubusercontent.com/assets/15726024/26619831/c24e22a4-4612-11e7-96f4-6b181aa4543c.png)

**Comment by star-andy** [comment]
@Jude95 
```java
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
	at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5690)
	at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:5797)
	at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:8352)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3610)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1633)
	at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:341)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:628)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by star-andy** [comment]
我的问题已经解决，我是在列表上动态添加head和remove head遇见的错误。
```java
if (videoBean.getVideos() != null && videoBean.getVideos().size() > 0) {
            mVideoAdapter.removeAllHeader();
            mVideoAdapter.addHeader(headItemView);
            videos = videoBean.getVideos();
            List<View> pagerList = createViewPager(videos);
            viewPagerAdapter = new VideoViewPagerAdapter(pagerList);
            mViewpager.setAdapter(viewPagerAdapter);
            if (!TextUtils.isEmpty(videoBean.getMatchName())) {
                headMatchName.setText(videoBean.getMatchName());
            }
            mVideoAdapter.addHeader(headItemTv);
            viewPagerAdapter.setOnPagerItemClickListener(new VideoViewPagerAdapter.OnItemClickListener() {
                @Override
                public void onItemClick(int posotion) {
                    startVideoPlay(videoBean.getVideos(), posotion, BaseConstant.VIDEO_VIEWPAGER, -1);
                }
            });
            mVideoList.scrollToPosition(0);
        } else {
            mVideoAdapter.removeAllHeader();
            mVideoAdapter.addHeader(headItemTv);
        }
        mVideoAdapter.notifyDataSetChanged();
```
最后加上了一句     mVideoAdapter.notifyDataSetChanged();解决问题
