### ISSUE TITLE
是不是不能在Fragment中使用setMore和setNoMore方法?

### ISSUE THREAD

**Issue by kncxstudio** [Jude95/EasyRecyclerView#68]
07-19 23:47:58.677 24335-24335/com.yuehu.cola.projectcola E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.yuehu.cola.projectcola, PID: 24335
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuehu.cola.projectcola/com.yuehu.cola.projectcola.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:135)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                                at android.view.ViewConfiguration.get(ViewConfiguration.java:359)
                                                                                at android.view.View.<init>(View.java:3587)
                                                                                at android.view.View.<init>(View.java:3682)
                                                                                at android.view.ViewGroup.<init>(ViewGroup.java:497)
                                                                                at android.view.ViewGroup.<init>(ViewGroup.java:493)
                                                                                at android.view.ViewGroup.<init>(ViewGroup.java:489)
                                                                                at android.view.ViewGroup.<init>(ViewGroup.java:485)
                                                                                at android.widget.FrameLayout.<init>(FrameLayout.java:103)
                                                                                at com.jude.easyrecyclerview.adapter.RecyclerArrayAdapter.setMore(RecyclerArrayAdapter.java:223)
                                                                                at com.yuehu.cola.projectcola.ui.fragments.FragmentYuehu.initViews(FragmentYuehu.java:70)
                                                                                at com.yuehu.cola.projectcola.ui.fragments.FragmentYuehu.onCreateView(FragmentYuehu.java:62)
                                                                                at android.app.Fragment.performCreateView(Fragment.java:2053)
                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                at android.app.BackStackRecord.run(BackStackRecord.java:834)
                                                                                at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
                                                                                at android.app.Activity.performStart(Activity.java:6005)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by Jude95** [comment]
没有区别，你应该贴一下代码和并说明下崩溃场景。

**Comment by kncxstudio** [comment]
已经解决，谢谢回复
