### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by gmfbilu** [Jude95/EasyRecyclerView#70]
android.view.InflateException: Binary XML file line #44: Error inflating class com.jude.easyrecyclerview.EasyRecyclerView
                                                                           at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                           at com.smzf100.saomatuan.homePage.fragment.ServiceFragment.onCreateView(ServiceFragment.java:91)
                                                                           at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                           at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                           at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
                                                                           at android.os.Handler.handleCallback(Handler.java:615)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)

魅族MX 安卓4.1

**Comment by Jude95** [comment]
新版本已解决
